name: github pages

on:
  push:
    branches:
      - deploy # default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g pnpm
      - run: pnpm install
      # 文档编译命令，如果是 react 模板需要修改为 npm run docs:build
      - run: npx nx run cool-web:export
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/packages/cool-web/exported